- name: copy mongodb repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongo
  ansible.builtin.dnf:
    name: mongodb-org
    state: present

- name: update mongo db config file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mongo db
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: yes