- name: add app user
  ansible.builtin.user:
    name: roboshop

- name: remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app content directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component_name }}-v3.zip
    dest: /app
    remote_src: yes