- name: disable nodejs and enable nodejs
  ansible.builtin.shell:
    dnf module nodejs-y; dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present