- name: disable nodejs and enable nodejs
  ansible.builtin.shell: dnf module nodejs -y ; dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: include artifact_download task
  ansible.builtin.include_tasks:
    file: artifact_download.yml
  
- name: install node js dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: include systemd_setup task
  ansible.builtin.include_tasks:
    file: systemd_setup.yml
